name: Build and Release CodePRobot Agent

on:
  pull_request:
    paths:
      - 'main.go'
      - 'go.mod'
      - 'go.sum'
      - 'cmd/**'
      - 'internal/**'
      - '.github/workflows/build-release.yml'
  schedule:
    - cron: '0 2 * * *'  # 每日 UTC 凌晨 2 点构建
  workflow_dispatch:

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build CodePRobot binary
        run: |
          mkdir -p dist
          go build -o dist/CodePRobot-${{ matrix.goos }}-${{ matrix.goarch }} main.go

      - name: Compress binary
        run: |
          cd dist
          tar -czvf CodePRobot-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz CodePRobot-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CodePRobot-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/CodePRobot-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz

  test:
    name: Test Linux CLI binaries by arch
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
        arch: [amd64, arm64]

    steps:
      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: CodePRobot-linux-${{ matrix.arch }}
          path: test-dir

      - name: Extract and test CLI
        run: |
          cd test-dir
          tar -xzf CodePRobot-linux-${{ matrix.arch }}.tar.gz
          chmod +x CodePRobot-linux-${{ matrix.arch }}
          ./CodePRobot-linux-${{ matrix.arch }} --help

  publish-release:
    name: Publish Daily Release
    needs: test
    runs-on: ubuntu-latest
    env:
      tag_name: daily-${{ github.run_id }}
      release_name: Daily Build CodePRobot - ${{ github.run_number }}

    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.tag_name }}
          name: ${{ env.release_name }}
          prerelease: true
          files: |

